### ISSUE TITLE
Unable to get link data on Windows 10

### ISSUE THREAD

**Issue by KMC123321** [chall32/LDWin#11]
C:\Temp>tcpdump.exe -d

---

---

*\*         Tcpdump v4.5.1 (Nov 20, 2013) for Windows             **
*\*    Win98/ME/NT4/2000/XP/2003/Vista/2008/Win7/Win8/Win2012     **

---

*\*      built with Microolap Packet Sniffer SDK v6.1 and         **
*\*   Microolap WinPCap to Packet Sniffer SDK migration module.   **

---

*\*                  (c) Microolap Technologies,                  **
*\*                  Khalturin A.P. & Naumov D.A.                 **
*\*                   http://www.microolap.com                    **

---

*\*                         Trial license.                        **

---

---

tcpdump.exe: listening on \Device{6990D8C0-6750-4521-B77D-708D3C2A9C40}
tcpdump.exe: : Error opening adapter: Overlapped I/O operation is in progress. (997)

This is using Windows 10 Enterprise Build 10586.318
I did run the TCPDUMP above as an administrator.

**Comment by KMC123321** [comment]
Oh, BTW, I could get this wonderful tool to work on a Windows 7 Enterprise client with the same network drop, so it isn't anything in the network infrastructure preventing the capture.

**Comment by chall32** [comment]
Please try with capital "D": `tcpdump.exe -D`

![screenshot from 2016-06-02 20 29 03](https://cloud.githubusercontent.com/assets/1158765/15758228/83be812a-2901-11e6-8a9b-0f747f88ec54.png)

**Comment by KMC123321** [comment]
Oops, should have expected case sensitivity from a Unix app ported to Windows :)
I don't get anything from the capture after letting it run for 5 minutes.

C:\Temp>tcpdump -D

---

---

*\*         Tcpdump v4.5.1 (Nov 20, 2013) for Windows             **
*\*    Win98/ME/NT4/2000/XP/2003/Vista/2008/Win7/Win8/Win2012     **

---

*\*      built with Microolap Packet Sniffer SDK v6.1 and         **
*\*   Microolap WinPCap to Packet Sniffer SDK migration module.   **

---

*\*                  (c) Microolap Technologies,                  **
*\*                  Khalturin A.P. & Naumov D.A.                 **
*\*                   http://www.microolap.com                    **

---

*\*                         Trial license.                        **

---

---

1.\Device{7C077B64-BB02-4D10-8195-0A0493E3C43A} (Intel(R) Ethernet Connection (3) I218-LM)
2.\Device{6990D8C0-6750-4521-B77D-708D3C2A9C40} (Bluetooth Device (Personal Area Network))
3.\Device{D72567B0-DC3A-4414-8716-A719B11924BC} (Intel(R) Dual Band Wireless-AC 7265)
4.\Device{667372EC-09F0-4F05-ABBE-5511EE41E26B} (Microsoft Wi-Fi Direct Virtual Adapter)

C:\Temp> tcpdump -i 1 -nn -v -s 1500 -c 1 (ether[12:2]==0x88cc or ether[20:2]==0x2000)

---

---

*\*         Tcpdump v4.5.1 (Nov 20, 2013) for Windows             **
*\*    Win98/ME/NT4/2000/XP/2003/Vista/2008/Win7/Win8/Win2012     **

---

*\*      built with Microolap Packet Sniffer SDK v6.1 and         **
*\*   Microolap WinPCap to Packet Sniffer SDK migration module.   **

---

*\*                  (c) Microolap Technologies,                  **
*\*                  Khalturin A.P. & Naumov D.A.                 **
*\*                   http://www.microolap.com                    **

---

*\*                         Trial license.                        **

---

---

tcpdump: listening on \Device{7C077B64-BB02-4D10-8195-0A0493E3C43A}

It is LLDP that we are using in this case, if that makes any difference.

**Comment by chall32** [comment]
Works fine for me under Windows 10:

![ldwin-win10](https://cloud.githubusercontent.com/assets/1158765/16200406/1a0403ba-3705-11e6-8054-0f8df5d2ee4f.PNG)

LLDP test info created using https://sourceforge.net/projects/lldpgenerator/ (run under Linux Mint)

**Comment by hawkeye0386** [comment]
I am also unable to get CDP data in Windows 10. This is in the new build however, 1603. The 1511 build was working correctly.

**Comment by KMC123321** [comment]
My issue turned out to be the Avaya IP phone interfering with the LLDP data coming from the switch. You might want to make sure you don't have anything between your Ethernet port and the switch or network port other than the cable.
