### ISSUE TITLE
EXE Flagged by virus vendors

### ISSUE THREAD

**Issue by ThreeSevenths** [chall32/LDWin#24]
Hello, like any good sysadmin, I checked the file before executing. According to VirusTotal, 5 different engines have potential issues with the EXE file in your repo. 

https://www.virustotal.com/gui/file/ed0bf3c3746fcaa8f4efcf12ad26c590cba709f229c0f4f8fc33e6df227b1872/detection

**Comment by tplane** [comment]
I found the same issue. Is going to be addressed?

**Comment by eatyourpeas747** [comment]
Same here yesterday with Windows Defender flagging it with PUA:Win32/CandyOpen

**Comment by ThreeSevenths** [comment]
I think this is closed because the problem is with the app that compiles the code, not this app itself.
