### ISSUE TITLE
No link data found

### ISSUE THREAD

**Issue by soepstad** [chall32/LDWin#3]
First of all, wonderful tool, thanks!

Ran into a little issue:

Lenovo Thinkpad t440s Win8.1. No link data found after ten minutes with LDW, but tcpdump gets it.

Tcpdump output:
C:\bin>tcpdump -i 5 -nn -v -s 1500 -c 1 (ether[12:2]==0x88cc or ether[20:2]==0x2
000)

*******************************************************************
**                                                               **
**         Tcpdump v4.5.1 (Nov 20, 2013) for Windows             **
**    Win98/ME/NT4/2000/XP/2003/Vista/2008/Win7/Win8/Win2012     **
**                                                               **
**      built with Microolap Packet Sniffer SDK v6.1 and         **
**   Microolap WinPCap to Packet Sniffer SDK migration module.   **
**                                                               **
**                  (c) Microolap Technologies,                  **
**                  Khalturin A.P. & Naumov D.A.                 **
**                   http://www.microolap.com                    **
**                                                               **
**                         Trial license.                        **
**                                                               **
*******************************************************************

tcpdump: listening on \Device\{779A0282-3E24-48DB-94CE-0A9A28EC7224}
09:41:16.781687 CDPv2, ttl: 180s, checksum: 692 (unverified), length 462
        Device-ID (0x01), length: 40 bytes: 'nnnn'
        Version String (0x05), length: 243 bytes:
          Cisco IOS Software, C3560 Software (C3560-IPBASEK9-M), Version 12.2(55
)SE8, RELEASE SOFTWARE (fc2)
          Technical Support: http://www.cisco.com/techsupport
          Copyright (c) 1986-2013 by Cisco Systems, Inc.
          Compiled Wed 26-Jun-13 11:18 by prod_rel_team
        Platform (0x06), length: 19 bytes: 'cisco WS-C3560-24TS'
        Address (0x02), length: 13 bytes: IPv4 (1) x.x.x.x
        Port-ID (0x03), length: 16 bytes: 'FastEthernet0/21'
        Capability (0x04), length: 4 bytes: (0x00000028): L2 Switch, IGMP snoopi
ng
        Protocol-Hello option (0x08), length: 32 bytes:
        VTP Management Domain (0x09), length: 3 bytes: 'nnnn'
        Native VLAN ID (0x0a), length: 2 bytes: xxx
        Duplex (0x0b), length: 1 byte: full
        ATA-186 VoIP VLAN request (0x0e), length: 3 bytes: app 1, vlan xxx
        AVVID trust bitmap (0x12), length: 1 byte: 0x01
        Management Addresses (0x16), length: 13 bytes: IPv4 (1) x.x.x.x
        unknown field type (0x1a), length: 12 bytes:
          0x0000:  0000 0001 0000 0000 ffff ffff
1 packet captured
255 packets received by filter
0 packets dropped by kernel

**Comment by chall32** [comment]
Sorry, have only just picked this up.  Is this still an issue?

**Comment by soepstad** [comment]
Yes, unfortunately. Also same hardware with Win7. Have since picked up a Fluke Linkrunner so it's less of an issue, but I'd still like to use this for remote locations.

**Comment by chall32** [comment]
OK, so I've run LDWin against a text file consisting of the data you posted above.  All Looks good:
![image](https://cloud.githubusercontent.com/assets/1158765/5991996/50d2d53a-aa0a-11e4-9f60-4ce8a174a243.png)

So the GUI is triggering and grabbing the correct data. Next question; I'm wondering if LDWin is timing out before the CDP packet is transmitted. In other words, a 60 second timeout might not be long enough.  I'm wondering do you have access to the switch?  If you do could you query the "cdp timer" value?  
See http://www.cisco.com/c/en/us/td/docs/ios/12_2/configfun/command/reference/ffun_r/frf015.html#wp1017615 for further info.

It might be that LDWin needs a customisable timeout setting!!

**Comment by soepstad** [comment]
Hi, sorry for the late reply. All my switches run with default timer settings, 60 seconds update interval, 180 seconds holdtime

**Comment by chall32** [comment]
Please try v2.2 If still issue, please open another issue ticket

Thanks!
