### ISSUE TITLE
Port name missing

### ISSUE THREAD

**Issue by tenox2** [chall32/LDWin#4]
LLDP and CDP are supposed to have both port Name and Description. The LDWin only displays the description. If switch ports have same description, or no description at all they are unidentifiable with the LDWin.

**Comment by chall32** [comment]
OK, I can see both port name and port description within the LLDP RFC (http://standards.ieee.org/getieee802/download/802.1AB-2009.pdf):
![image](https://cloud.githubusercontent.com/assets/1158765/5665417/2f9efa96-9750-11e4-926b-99a6a988ee1f.png)

Looking through LDWin source, agree it's possible we are triggering on the wrong TLV.

But I can't anything in the CDP spec for port description (http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/cdp/configuration/15-mt/cdp-15-mt-book/nm-cdp-discover.html#GUID-FF08358E-02BE-4E01-B2BB-1D1BEEB78C57)
![image](https://cloud.githubusercontent.com/assets/1158765/5665493/b775c148-9750-11e4-9fc2-65c1b094eb8f.png)
