### ISSUE TITLE
LDwin not detecting OneLink Pro Dock

### ISSUE THREAD

**Issue by danskeller10** [chall32/LDWin#5]
First off, great utility.  I tried this utility in mulitple configurations and all execpt one has returned the expected results.  

I recently refreshed my PC to a Lenovo X1 Carbon with an external OneLink Pro Dock with a Gigabit ethernet connection.  If I hardwire a network adapter via USB or tcpdump sees the interface, but LDWin does not.   Here is the output 

tcpdump -D

*******************************************************************
**                                                               **
**         Tcpdump v4.5.1 (Nov 20, 2013) for Windows             **
**    Win98/ME/NT4/2000/XP/2003/Vista/2008/Win7/Win8/Win2012     **
**                                                               **
**      built with Microolap Packet Sniffer SDK v6.1 and         **
**   Microolap WinPCap to Packet Sniffer SDK migration module.   **
**                                                               **
**                  (c) Microolap Technologies,                  **
**                  Khalturin A.P. & Naumov D.A.                 **
**                   http://www.microolap.com                    **
**                                                               **
**                         Trial license.                        **
**                                                               **
*******************************************************************

1.\Device\PssdkLoopback (PSSDK Loopback Ethernet Emulation Adapter)
2.\Device\NdisWanBh (WAN Miniport (Network Monitor))
3.\Device\{B426ECB8-3FDC-4738-8912-B236908F2BD4} (ThinkPad OneLink Pro Dock Giga Ethernet)
4.\Device\{AFA859BD-7559-4658-A21E-9DDA5A756377} (Intel(R) Dual Band Wireless-AC 7260)
5.\Device\{F9451C28-22FF-4DD9-AE40-6F5381981F7C} (Intel(R) Ethernet Connection I218-LM)

tcpdump -i 3 -nn -s 1500 -c 1 (ether[12:2]=0x88cc or ether[20:2]==0x2000)

*******************************************************************
**                                                               **
**         Tcpdump v4.5.1 (Nov 20, 2013) for Windows             **
**    Win98/ME/NT4/2000/XP/2003/Vista/2008/Win7/Win8/Win2012     **
**                                                               **
**      built with Microolap Packet Sniffer SDK v6.1 and         **
**   Microolap WinPCap to Packet Sniffer SDK migration module.   **
**                                                               **
**                  (c) Microolap Technologies,                  **
**                  Khalturin A.P. & Naumov D.A.                 **
**                   http://www.microolap.com                    **
**                                                               **
**                         Trial license.                        **
**                                                               **
*******************************************************************

tcpdump: listening on \Device\{B426ECB8-3FDC-4738-8912-B236908F2BD4}
09:23:15.117373 LLDP, length 142: SEP8CB64F57EF89.cisco.com
1 packet captured
307 packets received by filter
0 packets dropped by kernel

![image](https://cloud.githubusercontent.com/assets/12053818/7257329/d2536b1e-e809-11e4-9dae-e46ab8efe930.png)
The "Local Area Connection" lists the I218-LM network adapter"
The "Local Area Connection 2" (both of the entries) in the list show the network card as "Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Window x64".  

Thanks, 
Dan Keller

**Comment by chall32** [comment]
Hey Dan,

Yep, definitely something not quite right there!

When LDWin is started, it saves the information on network cards it finds via WMI into the file %temp%\LinkData.txt.  This file looks something like this:
** **
*[]
ProductName=WAN Miniport (SSTP)
SettingID={4AE6B55C-6DD6-427D-A5BB-13535D4BE926}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (IKEv2)
SettingID={FB474E6C-F93F-4848-945E-86780D2A9897}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (L2TP)
SettingID={66973E50-CF44-46A7-AD86-0F369D30ACA2}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (PPTP)
SettingID={F93EB786-8968-43C5-BC58-54D87385060E}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (PPPOE)
SettingID={6A16EDEB-24DF-416A-B427-CED88EFCA006}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (IPv6)
SettingID={F4373218-ED19-4F3D-8DB4-982009ED86B7}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (Network Monitor)
SettingID={5356FE17-48EE-4A7A-BECE-645E20060A52}
IPAddress=
MACAddress=
[Local Area Connection]
ProductName=Intel(R) PRO/1000 MT Network Connection
SettingID={6935456A-389E-427F-80DC-1C1E192660DD}
IPAddress=192.168.xx.xx
MACAddress=xx:xx:xx:xx:xx:xx
[]
ProductName=WAN Miniport (IP)
SettingID={66513FCE-F1B9-480C-B278-3DD588D5D452}
IPAddress=
MACAddress=
[]
ProductName=Microsoft Teredo Tunneling Adapter
SettingID={CE345F19-C9A3-4536-95D7-0D784BD4C98C}
IPAddress=
MACAddress=
[]
ProductName=RAS Async Adapter
SettingID={DD2F4800-0DEB-4A98-A302-0777CB955DC1}
IPAddress=
MACAddress=xx:xx:xx:xx:xx:xx*
** **
As you can see, there is a lot listed!  So that the user is presented with a list of physical interfaces, rather than the whole shooting match, LDWin filters this down. I'm guessing it's here that things are not going so smoothly.

Please can you start LDWin (no need to do anything other than launch it) and post back the contents of your %temp%\LinkData.txt ?

Thanks

**Comment by danskeller10** [comment]
Here is the enumerated list.  I can see the OneLink on the same 'Local Area Network 2' name as the Anyconnect  device.  not sure how the enumeration to drop down menu items occurs, but it looks like the app uses the same info for Network 2 and masks the OneLink.  BTW, if I choose either of the 'Local Area Network 2', they both show anyconnect and neither detects CDP/LLDP

Thanks, 
Dan


[]
ProductName=WAN Miniport (SSTP)
SettingID={71F897D7-EB7C-4D8D-89DB-AC80D9DD2270}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (IKEv2)
SettingID={29898C9D-B0A4-4FEF-BDB6-57A562022CEE}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (L2TP)
SettingID={E43D242B-9EAB-4626-A952-46649FBB939A}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (PPTP)
SettingID={DF4A9D2C-8742-4EB1-8703-D395C4183F33}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (PPPOE)
SettingID={8E301A52-AFFA-4F49-B9CA-C79096A1A056}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (IPv6)
SettingID={9A399D81-2EAD-4F23-BCDD-637FC13DCD51}
IPAddress=
MACAddress=
[]
ProductName=WAN Miniport (Network Monitor)
SettingID={5BF54C7E-91DA-457D-80BF-333677D7E316}
IPAddress=
MACAddress=
[Local Area Connection]
ProductName=Intel(R) Ethernet Connection I218-LM
SettingID={F9451C28-22FF-4DD9-AE40-6F5381981F7C}
IPAddress=
MACAddress=54:EE:75:37:6E:F0
[]
ProductName=WAN Miniport (IP)
SettingID={2CAA64ED-BAA3-4473-B637-DEC65A14C8AA}
IPAddress=
MACAddress=
[]
ProductName=Microsoft ISATAP Adapter
SettingID={282195F9-FCD4-48F0-BBE9-C2A8AF5F2A0B}
IPAddress=
MACAddress=
[]
ProductName=RAS Async Adapter
SettingID={78032B7E-4968-42D3-9F37-287EA86C0AAA}
IPAddress=
MACAddress=20:41:53:59:4E:FF
[Wireless Network Connection]
ProductName=Intel(R) Dual Band Wireless-AC 7260
SettingID={AFA859BD-7559-4658-A21E-9DDA5A756377}
IPAddress=171.68.21.132
MACAddress=E8:B1:FC:D2:5F:DC
[]
ProductName=Microsoft 6to4 Adapter
SettingID={AF6F3A1B-3FB6-463A-8E60-2DC55E0DCA68}
IPAddress=
MACAddress=
[]
ProductName=Microsoft ISATAP Adapter
SettingID={DD6993CD-58D4-41F3-86F5-1F348397D9D6}
IPAddress=
MACAddress=
[Bluetooth Network Connection]
ProductName=Bluetooth Device (Personal Area Network)
SettingID={A6872DF0-A33B-46D6-9758-35C1CDC7AB50}
IPAddress=
MACAddress=E8:B1:FC:D2:5F:E0
[Local Area Connection 2]
ProductName=Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
SettingID={302A2450-9BC4-41F3-B7DE-F12F747EB8BA}
IPAddress=
MACAddress=
[]
ProductName=Microsoft ISATAP Adapter
SettingID={010D0194-496C-44C2-B034-A91EE6E30821}
IPAddress=
MACAddress=
[Local Area Connection 2]
ProductName=ThinkPad OneLink Pro Dock Giga Ethernet
SettingID={B426ECB8-3FDC-4738-8912-B236908F2BD4}
IPAddress=10.35.132.39
MACAddress=00:50:B6:7D:B6:FF
[]
ProductName=Microsoft ISATAP Adapter
SettingID={8A3807A6-42BA-41ED-BE0C-F3637904C0F4}
IPAddress=
MACAddress=
[]
ProductName=Microsoft ISATAP Adapter
SettingID={5693CCF1-4D4D-4EFF-98F6-6FE791C90987}
IPAddress=
MACAddress=
[]
ProductName=Thinkpad USB 3.0 Ethernet Adapter
SettingID={684904AA-233A-4CB1-B9B2-B42C89E712F5}
IPAddress=
MACAddress=
[]
ProductName=Microsoft Teredo Tunneling Adapter
SettingID={A21906CD-06DB-44C9-AE1B-E9686CBEAEA9}
IPAddress=
MACAddress=
[]
ProductName=Microsoft ISATAP Adapter
SettingID={5DFFD0AC-508D-4F1E-8758-7E743337C464}
IPAddress=
MACAddress=

**Comment by chall32** [comment]
Dan,

OK, so you have two network cards with the same name and LDWin is getting confused.  Normally you aren't allowed to have that:

![image](https://cloud.githubusercontent.com/assets/1158765/7263662/8a67e146-e87b-11e4-9f76-e311c9d3e7a7.png)


Therefore, can you rename one of your Local Area Connection 2's? 
Something like "Local Area Connection 2-Dock" for the ThinkPad OneLink Pro Dock Giga Ethernet

That way when LDWin enumerates your NIC selection from the dropdown by looking for the appropriate section in%temp%\LinkData.txt it won't get confused.

Chris

**Comment by danskeller10** [comment]
Chris, 

Simply changing the duplicate name fixed the issue.  So under Network and Sharing Center, I went to Change Adapter Settings and modified the 'Local Area Connection 2' to 'Local Area Connection 2-OneLink' and I can now detect L2 CDP on that link.  Interesting enough, the Anyconnect device in the network connections list does not have a 'Local Area Connection 2' name.  It shows up as 'Cisco Anyconnect Secure Mobility Client' 
But problem solved.  Thanks for the support.

Thanks, 
Dan Keller
