### ISSUE TITLE
Can´t make it run in Win10

### ISSUE THREAD

**Issue by Mauricio-noGH** [chall32/LDWin#8]
Recenttly I upgraded to Win10, and can`t make LDWin work on it.

**Comment by chall32** [comment]
Please can you follow https://github.com/chall32/LDWin/wiki/What-To-Do-If-LDWin-Captures-No-Data to see if you can manually capture some data.  If you do capture some data form tcpdump, please can you post it here. Feel free to replace IP addresses / hostnames etc first.

**Comment by chall32** [comment]
Works fine for me under Windows 10:

![ldwin-win10](https://cloud.githubusercontent.com/assets/1158765/16200406/1a0403ba-3705-11e6-8054-0f8df5d2ee4f.PNG)

LLDP test info created using https://sourceforge.net/projects/lldpgenerator/
